"""Слой доступа к базе: одинаковое поведение на SQLite и Postgres.

Postgres-часть включается переменной RETRO_TEST_POSTGRES_URL. Без неё тесты
SQLite всё равно идут — набор не должен требовать поднятого сервера.
"""
import os
import sys
from decimal import Decimal

import pytest

from retro.db import (Database, is_postgres_url, needs_do_nothing, statements,
                      to_postgres)

POSTGRES_URL = os.getenv('RETRO_TEST_POSTGRES_URL', '')
needs_postgres = pytest.mark.skipif(not POSTGRES_URL, reason='RETRO_TEST_POSTGRES_URL не задан')

SCHEMA = '''
    CREATE TABLE IF NOT EXISTS probe_money (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        day TEXT NOT NULL,
        amount TEXT NOT NULL,
        note TEXT,
        photo BLOB
    );
    CREATE TABLE IF NOT EXISTS probe_unique (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS probe_money_day ON probe_money(day);
'''


# ── Перевод SQL ─────────────────────────────────────────────────────────────

def test_placeholders_are_translated_but_question_marks_in_text_survive():
    assert to_postgres('SELECT 1 WHERE a = ? AND b = ?') == 'SELECT 1 WHERE a = %s AND b = %s'
    # Знак вопроса внутри строкового литерала — часть данных, не плейсхолдер.
    assert to_postgres("SELECT 'всё ли ок?' WHERE a = ?") == "SELECT 'всё ли ок?' WHERE a = %s"


def test_ddl_divergences_are_translated():
    assert 'GENERATED BY DEFAULT AS IDENTITY' in to_postgres(
        'CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)')
    assert 'BYTEA' in to_postgres('CREATE TABLE t (photo BLOB)')
    assert 'AUTOINCREMENT' not in to_postgres(
        'CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)')


def test_insert_or_ignore_becomes_on_conflict_do_nothing():
    assert needs_do_nothing('INSERT OR IGNORE INTO t (a) VALUES (?)')
    # Если конфликт уже описан явно, второй раз дописывать нельзя.
    assert not needs_do_nothing('INSERT OR IGNORE INTO t (a) VALUES (?) ON CONFLICT DO NOTHING')
    assert not needs_do_nothing('INSERT INTO t (a) VALUES (?)')


def test_script_splits_into_statements():
    assert len(statements(SCHEMA)) == 3
    assert statements('   ') == []


def test_postgres_urls_are_recognised():
    assert is_postgres_url('postgresql://user:pass@host:5432/db')
    assert is_postgres_url('postgres://host/db')
    assert not is_postgres_url('/var/data/cashier.sqlite3')
    assert not is_postgres_url('')


# ── Одинаковое поведение на обоих диалектах ─────────────────────────────────

def databases(tmp_path):
    result = [('sqlite', Database(tmp_path / 'probe.sqlite3'))]
    if POSTGRES_URL:
        result.append(('postgres', Database(POSTGRES_URL)))
    return result


def prepare(database):
    with database.cursor() as connection:
        if database.is_postgres:
            connection.execute('DROP TABLE IF EXISTS probe_money')
            connection.execute('DROP TABLE IF EXISTS probe_unique')
            connection.commit()
        connection.executescript(SCHEMA)
        connection.commit()


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_same_behaviour_on_both_dialects(tmp_path, label):
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)

    with database.cursor() as connection:
        # id возвращается там, где раньше читали lastrowid
        first = database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount, note) VALUES (?, ?, ?)',
            ('2026-09-16', '108000.00', 'Помидоры'))
        second = database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount, note) VALUES (?, ?, ?)',
            ('2026-09-17', '80000.00', 'Лук'))
        connection.commit()
        assert isinstance(first, int) and second > first

        # Даты лежат текстом и сравниваются как текст — одинаково в обеих БД.
        rows = connection.execute(
            'SELECT day, amount FROM probe_money WHERE day >= ? ORDER BY day',
            ('2026-09-17',)).fetchall()
        assert [tuple(row) for row in rows] == [('2026-09-17', '80000.00')]

        # Деньги не теряют копейки: TEXT отдаётся ровно тем же.
        amount = connection.execute('SELECT amount FROM probe_money WHERE id = ?',
                                    (first,)).fetchone()[0]
        assert amount == '108000.00'

        # rowcount нужен коду удаления
        deleted = connection.execute('DELETE FROM probe_money WHERE id = ?', (second,))
        assert deleted.rowcount == 1
        connection.commit()


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_photo_survives_as_bytes_on_both_dialects(tmp_path, label):
    """Фото закупа лежит BLOB/BYTEA — оно должно вернуться байт в байт."""
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)
    photo = bytes(range(256))
    with database.cursor() as connection:
        row_id = database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount, photo) VALUES (?, ?, ?)',
            ('2026-09-16', '1', photo))
        connection.commit()
        stored = connection.execute('SELECT photo FROM probe_money WHERE id = ?',
                                    (row_id,)).fetchone()[0]
        assert bytes(stored) == photo


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_insert_or_ignore_keeps_the_first_value_on_both_dialects(tmp_path, label):
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)
    with database.cursor() as connection:
        connection.execute('INSERT OR IGNORE INTO probe_unique (key, value) VALUES (?, ?)',
                           ('день', 'первое'))
        connection.execute('INSERT OR IGNORE INTO probe_unique (key, value) VALUES (?, ?)',
                           ('день', 'второе'))
        connection.commit()
        assert connection.execute('SELECT value FROM probe_unique WHERE key = ?',
                                  ('день',)).fetchone()[0] == 'первое'


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_rollback_undoes_the_whole_operation_on_both_dialects(tmp_path, label):
    """Деньги пишутся транзакцией: незавершённая операция не оставляет следа."""
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)
    with database.cursor() as connection:
        connection.execute('BEGIN IMMEDIATE')
        database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount) VALUES (?, ?)',
            ('2026-09-16', '500000'))
        connection.rollback()
        assert connection.execute('SELECT COUNT(*) FROM probe_money').fetchone()[0] == 0


# ── История ставок без триггеров ────────────────────────────────────────────

def roster_for(tmp_path, label):
    """Реестр на выбранном диалекте, с чистой схемой."""
    from retro.modules.accountant.roster import RosterStore
    if label == 'postgres':
        if not POSTGRES_URL:
            pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
        database = Database(POSTGRES_URL)
        with database.cursor() as connection:
            for table in ('accountant_employee_versions', 'accountant_roster_audit',
                          'accountant_monthly_employees', 'accountant_employees'):
                connection.execute(f'DROP TABLE IF EXISTS {table} CASCADE')
            connection.commit()
        return RosterStore(database)
    return RosterStore(tmp_path / 'roster.sqlite3')


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_history_is_written_by_code_on_both_dialects(tmp_path, label):
    """Историю ставок ведёт код, а не триггеры SQLite.

    `list(day)` берёт версию с наибольшим effective_day <= день, поэтому старая
    ставка обязана сохраниться за прошлые дни: начисления за них уже закрыты.
    """
    from datetime import date, timedelta
    roster = roster_for(tmp_path, label)
    person = roster.add(name='Жасур Алиев', role='официант', rate='200000',
                        group_name='Обслуживание зала')

    # Новый сотрудник виден и в прошлом: иначе прошлые смены его потеряют.
    past = date(2026, 1, 1)
    assert [p.name for p in roster.list(past)] == ['Жасур Алиев']
    assert roster.list(past)[0].rate == Decimal('200000')

    roster.update(person.id, name='Жасур Алиев', role='официант', rate='275000',
                  group_name='Обслуживание зала', reason='Повышение')

    # Сегодня — новая ставка, в прошлом — прежняя.
    assert roster.list()[0].rate == Decimal('275000')
    assert roster.list(past)[0].rate == Decimal('200000')

    roster.delete(person.id)
    assert roster.list() == []
    # Удалённый остаётся в прошлом: смены до удаления он отработал.
    assert [p.name for p in roster.list(past)] == ['Жасур Алиев']
    # А на завтра его уже нет.
    assert roster.list(date.today() + timedelta(days=1)) == []


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_no_write_path_loses_history(tmp_path, label):
    """Каждый путь записи обязан оставить версию.

    Раньше это гарантировали триггеры на любой INSERT/UPDATE/DELETE. Теперь —
    вызовы в коде, и пропущенный путь тихо перестал бы вести историю.
    """
    from retro.integrations.hikvision import HikvisionPerson
    roster = roster_for(tmp_path, label)
    first = roster.add(name='Азиз Каримов', role='менеджер', rate='400000',
                       group_name='Управление')
    second = roster.add(name='Лола Нурматова', role='техперсонал', rate='140000',
                        group_name='Уборка')

    def versions(employee_id):
        with roster._open() as connection:
            return connection.execute(
                'SELECT COUNT(*) FROM accountant_employee_versions WHERE employee_id = ?',
                (employee_id,)).fetchone()[0]

    assert versions(first.id) == 1 and versions(second.id) == 1

    # Привязка Hikvision — тоже правка реестра.
    roster.link_hikvision_people((HikvisionPerson('hik-1', 'Азиз Каримов'),))
    assert versions(first.id) >= 1
    with roster._open() as connection:
        linked = connection.execute(
            'SELECT hikvision_id FROM accountant_employee_versions '
            'WHERE employee_id = ? ORDER BY effective_day DESC LIMIT 1',
            (first.id,)).fetchone()[0]
    assert linked == 'hik-1', 'привязка должна попасть в историю'

    # Ручная отметка присутствия.
    roster.set_manual_attendance(second.id, True)
    assert versions(second.id) >= 1


def test_schema_no_longer_creates_sqlite_triggers(tmp_path):
    """Триггеры должны быть снесены: иначе на SQLite история писалась бы дважды."""
    from retro.modules.accountant.roster import RosterStore
    roster = RosterStore(tmp_path / 'roster.sqlite3')
    with roster._open() as connection:
        triggers = [row[0] for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type = 'trigger' "
            "AND name LIKE 'accountant_employee_%'")]
    assert triggers == []


# ── Страховка от молчаливой потери данных ───────────────────────────────────

def test_hosting_without_storage_refuses_to_start():
    """На хостинге без Postgres и без диска подниматься нельзя.

    Молчаливый откат на файлы внутри контейнера уже терял реестр и начисления:
    выкат выглядел успешным, данные исчезали. Упавший выкат видно сразу.
    """
    from retro.config import require_durable_storage
    railway = {'RAILWAY_ENVIRONMENT': 'production'}
    with pytest.raises(ValueError, match='Негде хранить данные'):
        require_durable_storage('', railway)


def test_postgres_or_an_explicit_disk_are_both_accepted():
    from retro.config import require_durable_storage
    railway = {'RAILWAY_ENVIRONMENT': 'production'}
    # Postgres — основной путь.
    require_durable_storage('postgresql://host/db', railway)
    # Диск, подключённый осознанно, тоже годится.
    require_durable_storage('', {**railway, 'RETRO_DATA_DIR': '/data'})


def test_local_machine_keeps_working_on_files():
    """Локальная разработка и тесты не должны требовать ни Postgres, ни диска."""
    from retro.config import require_durable_storage
    require_durable_storage('', {'HOME': '/home/user'})


# ── Перенос данных в Postgres ───────────────────────────────────────────────

@needs_postgres
def test_migration_moves_rows_money_and_photos_then_verifies(tmp_path):
    """Перенос обязан сойтись по строкам и суммам, а фото выжить байт в байт."""
    import subprocess
    from datetime import date, datetime
    from retro.modules.accountant.ledger import FinanceStore
    from retro.modules.shokh.store import ShokhStore

    source = tmp_path / 'accountant.sqlite3'
    finance, shokh = FinanceStore(source), ShokhStore(source)
    finance.record_handover(date(2026, 9, 16), Decimal('9000000'))
    photo = b'\x89PNG\r\n\x1a\n' + bytes(range(48))
    shokh.add_purchase(date(2026, 9, 16), datetime(2026, 9, 16, 10, 0), point='Базар',
                       item='Лук', unit='кг', quantity='10', price='3200',
                       photo=photo, photo_type='image/png')

    target = Database(POSTGRES_URL)
    with target.cursor() as connection:
        connection.execute('DROP SCHEMA public CASCADE')
        connection.execute('CREATE SCHEMA public')
        connection.commit()

    done = subprocess.run(
        [sys.executable, 'scripts/migrate_to_postgres.py', '--target', POSTGRES_URL,
         '--accountant', str(source), '--apply'],
        capture_output=True, text=True, env={**os.environ, 'PYTHONPATH': '.'})
    assert done.returncode == 0, done.stdout + done.stderr
    assert 'суммы совпали' in done.stdout

    # Деньги и фото на месте.
    moved = ShokhStore(target).purchases(date(2026, 9, 16))
    assert [(row['item'], row['total']) for row in moved] == [('Лук', '32000.00')]
    assert ShokhStore(target).photo(moved[0]['id'])[0] == photo
    with target.cursor() as connection:
        assert connection.execute(
            'SELECT amount FROM accountant_handover_days').fetchone()[0] == '9000000'

    # Счётчик номеров сдвинут: новая запись не сталкивается с перенесённой.
    fresh = ShokhStore(target).add_purchase(
        date(2026, 9, 17), datetime(2026, 9, 17, 9, 0), point='Базар', item='Мясо',
        unit='кг', quantity='5', price='80000')
    assert fresh['id'] > moved[0]['id']

    # Повторный запуск поверх данных запрещён: иначе начисления удвоятся.
    again = subprocess.run(
        [sys.executable, 'scripts/migrate_to_postgres.py', '--target', POSTGRES_URL,
         '--accountant', str(source), '--apply'],
        capture_output=True, text=True, env={**os.environ, 'PYTHONPATH': '.'})
    assert again.returncode == 1
    assert 'не пуст' in again.stdout


@needs_postgres
def test_dry_run_changes_nothing(tmp_path):
    import subprocess
    from datetime import date
    from retro.modules.cashier.expenses import ExpenseStore

    source = tmp_path / 'cashier.sqlite3'
    ExpenseStore(source).add(date(2026, 9, 16), 'Такси', '50000')
    target = Database(POSTGRES_URL)
    with target.cursor() as connection:
        connection.execute('DROP SCHEMA public CASCADE')
        connection.execute('CREATE SCHEMA public')
        connection.commit()

    done = subprocess.run(
        [sys.executable, 'scripts/migrate_to_postgres.py', '--target', POSTGRES_URL,
         '--cashier', str(source), '--dry-run'],
        capture_output=True, text=True, env={**os.environ, 'PYTHONPATH': '.'})
    assert done.returncode == 0
    assert 'ничего не изменено' in done.stdout
    # Схему dry-run тоже не создаёт.
    with target.cursor() as connection:
        tables = connection.execute(
            "SELECT COUNT(*) FROM information_schema.tables "
            "WHERE table_schema = 'public'").fetchone()[0]
    assert tables == 0
