"""Слой доступа к базе: одинаковое поведение на SQLite и Postgres.

Postgres-часть включается переменной RETRO_TEST_POSTGRES_URL. Без неё тесты
SQLite всё равно идут — набор не должен требовать поднятого сервера.
"""
import os

import pytest

from retro.db import (Database, is_postgres_url, needs_do_nothing, statements,
                      to_postgres)

POSTGRES_URL = os.getenv('RETRO_TEST_POSTGRES_URL', '')
needs_postgres = pytest.mark.skipif(not POSTGRES_URL, reason='RETRO_TEST_POSTGRES_URL не задан')

SCHEMA = '''
    CREATE TABLE IF NOT EXISTS probe_money (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        day TEXT NOT NULL,
        amount TEXT NOT NULL,
        note TEXT,
        photo BLOB
    );
    CREATE TABLE IF NOT EXISTS probe_unique (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS probe_money_day ON probe_money(day);
'''


# ── Перевод SQL ─────────────────────────────────────────────────────────────

def test_placeholders_are_translated_but_question_marks_in_text_survive():
    assert to_postgres('SELECT 1 WHERE a = ? AND b = ?') == 'SELECT 1 WHERE a = %s AND b = %s'
    # Знак вопроса внутри строкового литерала — часть данных, не плейсхолдер.
    assert to_postgres("SELECT 'всё ли ок?' WHERE a = ?") == "SELECT 'всё ли ок?' WHERE a = %s"


def test_ddl_divergences_are_translated():
    assert 'GENERATED BY DEFAULT AS IDENTITY' in to_postgres(
        'CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)')
    assert 'BYTEA' in to_postgres('CREATE TABLE t (photo BLOB)')
    assert 'AUTOINCREMENT' not in to_postgres(
        'CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)')


def test_insert_or_ignore_becomes_on_conflict_do_nothing():
    assert needs_do_nothing('INSERT OR IGNORE INTO t (a) VALUES (?)')
    # Если конфликт уже описан явно, второй раз дописывать нельзя.
    assert not needs_do_nothing('INSERT OR IGNORE INTO t (a) VALUES (?) ON CONFLICT DO NOTHING')
    assert not needs_do_nothing('INSERT INTO t (a) VALUES (?)')


def test_script_splits_into_statements():
    assert len(statements(SCHEMA)) == 3
    assert statements('   ') == []


def test_postgres_urls_are_recognised():
    assert is_postgres_url('postgresql://user:pass@host:5432/db')
    assert is_postgres_url('postgres://host/db')
    assert not is_postgres_url('/var/data/cashier.sqlite3')
    assert not is_postgres_url('')


# ── Одинаковое поведение на обоих диалектах ─────────────────────────────────

def databases(tmp_path):
    result = [('sqlite', Database(tmp_path / 'probe.sqlite3'))]
    if POSTGRES_URL:
        result.append(('postgres', Database(POSTGRES_URL)))
    return result


def prepare(database):
    with database.cursor() as connection:
        if database.is_postgres:
            connection.execute('DROP TABLE IF EXISTS probe_money')
            connection.execute('DROP TABLE IF EXISTS probe_unique')
            connection.commit()
        connection.executescript(SCHEMA)
        connection.commit()


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_same_behaviour_on_both_dialects(tmp_path, label):
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)

    with database.cursor() as connection:
        # id возвращается там, где раньше читали lastrowid
        first = database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount, note) VALUES (?, ?, ?)',
            ('2026-09-16', '108000.00', 'Помидоры'))
        second = database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount, note) VALUES (?, ?, ?)',
            ('2026-09-17', '80000.00', 'Лук'))
        connection.commit()
        assert isinstance(first, int) and second > first

        # Даты лежат текстом и сравниваются как текст — одинаково в обеих БД.
        rows = connection.execute(
            'SELECT day, amount FROM probe_money WHERE day >= ? ORDER BY day',
            ('2026-09-17',)).fetchall()
        assert [tuple(row) for row in rows] == [('2026-09-17', '80000.00')]

        # Деньги не теряют копейки: TEXT отдаётся ровно тем же.
        amount = connection.execute('SELECT amount FROM probe_money WHERE id = ?',
                                    (first,)).fetchone()[0]
        assert amount == '108000.00'

        # rowcount нужен коду удаления
        deleted = connection.execute('DELETE FROM probe_money WHERE id = ?', (second,))
        assert deleted.rowcount == 1
        connection.commit()


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_photo_survives_as_bytes_on_both_dialects(tmp_path, label):
    """Фото закупа лежит BLOB/BYTEA — оно должно вернуться байт в байт."""
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)
    photo = bytes(range(256))
    with database.cursor() as connection:
        row_id = database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount, photo) VALUES (?, ?, ?)',
            ('2026-09-16', '1', photo))
        connection.commit()
        stored = connection.execute('SELECT photo FROM probe_money WHERE id = ?',
                                    (row_id,)).fetchone()[0]
        assert bytes(stored) == photo


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_insert_or_ignore_keeps_the_first_value_on_both_dialects(tmp_path, label):
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)
    with database.cursor() as connection:
        connection.execute('INSERT OR IGNORE INTO probe_unique (key, value) VALUES (?, ?)',
                           ('день', 'первое'))
        connection.execute('INSERT OR IGNORE INTO probe_unique (key, value) VALUES (?, ?)',
                           ('день', 'второе'))
        connection.commit()
        assert connection.execute('SELECT value FROM probe_unique WHERE key = ?',
                                  ('день',)).fetchone()[0] == 'первое'


@pytest.mark.parametrize('label', ['sqlite', 'postgres'])
def test_rollback_undoes_the_whole_operation_on_both_dialects(tmp_path, label):
    """Деньги пишутся транзакцией: незавершённая операция не оставляет следа."""
    found = dict(databases(tmp_path))
    if label not in found:
        pytest.skip('RETRO_TEST_POSTGRES_URL не задан')
    database = found[label]
    prepare(database)
    with database.cursor() as connection:
        connection.execute('BEGIN IMMEDIATE')
        database.insert_returning_id(
            connection, 'INSERT INTO probe_money (day, amount) VALUES (?, ?)',
            ('2026-09-16', '500000'))
        connection.rollback()
        assert connection.execute('SELECT COUNT(*) FROM probe_money').fetchone()[0] == 0
