"""Один слой доступа к базе: Postgres в продакшене, SQLite локально и в тестах.

Зачем так. На Railway у приложения нет диска, а SQLite — это файл, поэтому
рабочие данные живут в Postgres и переживают выкат. Но 538 тестов не должны
требовать поднятого сервера: для них остаётся файловый SQLite, и набор тестов
по-прежнему гоняется одной командой.

Расхождения диалектов узкие, потому что код изначально писался переносимо:
строк-фабрик нет (строки — кортежи), даты и деньги хранятся ISO-текстом и
сравниваются как текст, функций вида `strftime` в SQL нет. Остаётся механика:

* плейсхолдеры `?` → `%s`;
* `INTEGER PRIMARY KEY AUTOINCREMENT` → `GENERATED BY DEFAULT AS IDENTITY`;
* `BLOB` → `BYTEA`;
* `lastrowid` → `RETURNING id` (см. `insert_returning_id`);
* `BEGIN IMMEDIATE` → обычный `BEGIN`: в Postgres конфликт разрешает сама
  СУБД, а не блокировка файла;
* `INSERT OR IGNORE` → `INSERT ... ON CONFLICT DO NOTHING`;
* `PRAGMA` игнорируется.

Переписывание SQL выбрано осознанно вместо правки 242 запросов руками: две
механические замены проверяются тестом, а двести ручных правок в денежном коде
— нет.
"""
import re
import sqlite3
import threading
from collections import deque
from contextlib import closing, contextmanager
from time import monotonic
from pathlib import Path
from urllib.parse import urlparse

from retro.runtime import secure_directory, secure_file

POSTGRES_SCHEMES = ('postgres', 'postgresql')


def is_postgres_url(value) -> bool:
    if not value:
        return False
    return urlparse(str(value)).scheme.split('+')[0] in POSTGRES_SCHEMES


# ── Перевод SQL ─────────────────────────────────────────────────────────────

_PLACEHOLDER = re.compile(r"""\?(?=(?:[^']*'[^']*')*[^']*$)""")


def to_postgres(sql: str) -> str:
    """SQLite-запрос → Postgres. Только механика, без разбора смысла."""
    sql = _PLACEHOLDER.sub('%s', sql)
    sql = re.sub(r'\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b',
                 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql, flags=re.I)
    sql = re.sub(r'\bINSERT\s+OR\s+IGNORE\s+INTO\b', 'INSERT INTO', sql, flags=re.I)
    sql = re.sub(r'\bINSERT\s+OR\s+REPLACE\s+INTO\b', 'INSERT INTO', sql, flags=re.I)
    sql = re.sub(r'\bBLOB\b', 'BYTEA', sql, flags=re.I)
    return sql


def needs_do_nothing(sql: str) -> bool:
    """`INSERT OR IGNORE` в Postgres требует явного `ON CONFLICT DO NOTHING`."""
    return bool(re.search(r'\bINSERT\s+OR\s+IGNORE\b', sql, flags=re.I)) \
        and 'ON CONFLICT' not in sql.upper()


def without_comments(sql: str) -> str:
    """SQL без ведущих строк-комментариев: по началу команды принимаются решения."""
    lines = [line for line in sql.strip().splitlines()
             if not line.strip().startswith('--')]
    return '\n'.join(lines).strip()


def statements(script: str):
    """`executescript` → отдельные команды. Точка с запятой внутри строк не
    встречается в нашем DDL, поэтому хватает простого разбиения."""
    return [part.strip() for part in script.split(';') if part.strip()]


# ── Соединения ──────────────────────────────────────────────────────────────

_DDL = re.compile(r'\s*(CREATE|ALTER|DROP)\s', re.I)
_INSERT_TABLE = re.compile(r'\bINSERT\s+(?:OR\s+\w+\s+)?INTO\s+([a-z_][a-z0-9_]*)', re.I)
_CREATE_TABLE = re.compile(
    r'CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-z_][a-z0-9_]*)\s*\((.*)', re.I | re.S)


def table_declares_id(statement: str) -> str | None:
    """Имя таблицы, если её DDL объявляет автономер `id`.

    Нужно, чтобы знать, где в Postgres дописывать `RETURNING id` вместо
    `lastrowid`. Список собирается из самого DDL, а не задаётся руками, — иначе
    новая таблица однажды тихо начнёт возвращать `None` вместо номера.
    """
    found = _CREATE_TABLE.search(statement)
    if not found:
        return None
    name, body = found.group(1), found.group(2)
    if re.search(r'\bid\s+(?:INTEGER|BIGINT)[^,]*\b(?:AUTOINCREMENT|IDENTITY)\b', body, re.I):
        return name
    return None


# ── Пул соединений Postgres ─────────────────────────────────────────────────
#
# Хранилища открывают соединение на каждую операцию: так писался код под
# SQLite, где открыть файл почти ничего не стоит. В Postgres каждое новое
# соединение — TCP, рукопожатие и SCRAM-авторизация, и «Неделя» учредителя
# открывала их ~200 за один запрос. Поэтому закрытое соединение не рвётся,
# а откладывается и отдаётся следующей операции.
#
# Пул свой, а не psycopg_pool: у того на каждую базу свои фоновые потоки, а
# тесты заводят сотни схем (своя строка подключения у каждой). Здесь потоков
# нет, и общий потолок простаивающих соединений держится на все базы сразу.

POOL_MAX_IDLE = 12         # простаивающих соединений на все базы разом
POOL_IDLE_SECONDS = 300    # дольше в запасе не держим: закрываем
POOL_CHECK_AFTER = 2.0     # пролежавшее дольше проверяем пустым запросом


class ConnectionPool:
    def __init__(self, *, max_idle=POOL_MAX_IDLE, idle_seconds=POOL_IDLE_SECONDS,
                 check_after=POOL_CHECK_AFTER, clock=monotonic):
        self.max_idle, self.idle_seconds, self.check_after = max_idle, idle_seconds, check_after
        self.clock = clock
        self._idle = deque()   # (url, raw, отложено_в); справа — свежие
        self._lock = threading.Lock()

    def acquire(self, url):
        import psycopg
        while True:
            found = self._take(url)
            if found is None:
                return psycopg.connect(url, autocommit=False)
            raw, idle_for = found
            if idle_for <= self.check_after or self._alive(raw):
                return raw
            _close_quietly(raw)

    def release(self, url, raw):
        from psycopg.pq import TransactionStatus
        if raw.closed:
            return
        try:
            # Операция, которая только читала, коммит не делает: транзакция
            # открыта. Раньше её откатывал разрыв соединения, теперь — мы.
            if raw.info.transaction_status != TransactionStatus.IDLE:
                raw.rollback()
            reusable = raw.info.transaction_status == TransactionStatus.IDLE
        except Exception:
            reusable = False
        if not reusable:
            _close_quietly(raw)
            return
        evicted = []
        with self._lock:
            self._idle.append((url, raw, self.clock()))
            while len(self._idle) > self.max_idle:
                evicted.append(self._idle.popleft()[1])
        for old in evicted:
            _close_quietly(old)

    def close_all(self):
        with self._lock:
            idle, self._idle = list(self._idle), deque()
        for _, raw, _ in idle:
            _close_quietly(raw)

    def _take(self, url):
        now = self.clock()
        stale, found = [], None
        with self._lock:
            for item in list(self._idle):
                if now - item[2] > self.idle_seconds:
                    self._idle.remove(item)
                    stale.append(item[1])
            # Берём самое свежее: оно вероятнее всего живо и уже прогрето.
            for index in range(len(self._idle) - 1, -1, -1):
                if self._idle[index][0] == url:
                    _, raw, since = self._idle[index]
                    del self._idle[index]
                    found = (raw, now - since)
                    break
        for raw in stale:
            _close_quietly(raw)
        return found

    @staticmethod
    def _alive(raw):
        # Как check_connection в psycopg_pool: пустой запрос вне транзакции,
        # одна поездка до сервера вместо нового рукопожатия.
        try:
            raw.autocommit = True
            raw.execute('')
            raw.autocommit = False
            return True
        except Exception:
            return False


def _close_quietly(raw):
    try:
        raw.close()
    except Exception:
        pass


POOL = ConnectionPool()


class _Released:
    """Место соединения, которое уже вернули в пул: им пользуется другая
    операция, и случайное обращение должно падать, а не писать в чужую
    транзакцию."""
    closed = True

    def __getattr__(self, name):
        import psycopg
        raise psycopg.OperationalError('the connection is closed')


class PostgresConnection:
    """Обёртка, чтобы код хранилищ не различал диалекты.

    Нужна ровно для того, чтобы `connection.execute('... ?', params)` работал
    там же, где раньше работал sqlite3. Всё остальное отдаём psycopg как есть.
    """

    def __init__(self, raw, database=None, pool=None):
        self._raw = raw
        self._database = database
        self._pool = pool

    def execute(self, sql, params=()):
        if needs_do_nothing(sql):
            sql = sql.rstrip().rstrip(';') + ' ON CONFLICT DO NOTHING'
        text = to_postgres(sql)
        # Решения принимаем по самой команде, а не по комментарию перед ней.
        stripped = without_comments(text).upper()
        if stripped.startswith('CREATE TABLE'):
            self._remember_table(sql)
        if stripped.startswith('BEGIN IMMEDIATE'):
            text = 'BEGIN'
        if stripped.startswith('PRAGMA'):
            return _Empty()
        # Триггеры истории ставок существовали только в SQLite-базах, и их
        # сносит миграция. В Postgres сносить нечего, а синтаксис там иной
        # (нужен ON таблица), поэтому такие команды просто пропускаем.
        if stripped.startswith('DROP TRIGGER'):
            return _Empty()
        # `lastrowid` в psycopg не работает, поэтому у таблиц с автономером
        # добираем номер через RETURNING и отдаём его тем же полем.
        wants_id = False
        if self._database is not None and stripped.startswith('INSERT'):
            found = _INSERT_TABLE.search(text)
            if (found and found.group(1).lower() in self._database.tables_with_id
                    and 'RETURNING' not in stripped):
                text = text.rstrip().rstrip(';') + ' RETURNING id'
                wants_id = True
        cursor = self._raw.cursor()
        cursor.execute(text, tuple(params) if params else None)
        if wants_id:
            return _WithId(cursor)
        # SQLite фиксирует DDL сам, Postgres — нет, и схема откатывалась при
        # закрытии соединения. Схема у нас всегда идемпотентная (IF NOT EXISTS),
        # поэтому фиксируем её сразу, как это делает SQLite.
        if _DDL.match(stripped):
            self._raw.commit()
        return cursor

    def executemany(self, sql, rows):
        cursor = self._raw.cursor()
        cursor.executemany(to_postgres(sql), [tuple(row) for row in rows])
        return cursor

    def executescript(self, script):
        for statement in statements(script):
            self._remember_table(statement)
            self.execute(statement)
        return self

    def _remember_table(self, statement):
        name = table_declares_id(statement)
        if name and self._database is not None:
            self._database.tables_with_id.add(name)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        raw, self._raw = self._raw, _Released()
        if isinstance(raw, _Released):
            return
        if self._pool is not None and self._database is not None:
            self._pool.release(self._database.url, raw)
        else:
            raw.close()

    # `with closing(conn) as c, c:` — второй `with` открывает транзакцию.
    # Как в sqlite3: на выходе фиксируем или откатываем, но НЕ закрываем.
    # psycopg на выходе из `with` закрывает соединение, и код, который после
    # блока транзакции ещё читал тем же соединением (касса: авто-строки
    # политики, затем выборка), на Postgres падал «the connection is closed».
    # Закрывает соединение внешний `closing(...)`.
    def __enter__(self):
        return self

    def __exit__(self, error_type, error, traceback):
        if self._raw.closed:
            return False
        if error_type is None:
            self._raw.commit()
        else:
            self._raw.rollback()
        return False


class _WithId:
    """Курсор INSERT с уже прочитанным номером: код ждёт `lastrowid`."""

    def __init__(self, cursor):
        self._cursor = cursor
        row = cursor.fetchone()
        self.lastrowid = row[0] if row else None
        self.rowcount = cursor.rowcount

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


class _Empty:
    """Ответ на `PRAGMA`, которого в Postgres нет."""
    rowcount = 0
    lastrowid = None

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


class Database:
    """Откуда брать соединение. Хранилища получают её вместо пути к файлу."""

    def __init__(self, target, *, name=''):
        self.name = name
        self.url = str(target) if is_postgres_url(target) else ''
        self.path = None if self.url else Path(target)
        # Таблицы с автономером: заполняется при создании схемы, нужно для
        # RETURNING id вместо lastrowid.
        self.tables_with_id = set()
        if self.path is not None:
            secure_directory(self.path.parent)

    @property
    def is_postgres(self) -> bool:
        return bool(self.url)

    def connect(self):
        if not self.is_postgres:
            connection = sqlite3.connect(self.path, timeout=10)
            secure_file(self.path)
            connection.execute('PRAGMA foreign_keys = ON')
            return connection
        return PostgresConnection(POOL.acquire(self.url), self, POOL)

    @contextmanager
    def cursor(self):
        """Соединение на одну операцию, с закрытием."""
        with closing(self.connect()) as connection:
            yield connection

    def insert_returning_id(self, connection, sql, params=()):
        """Вставка с получением id: `lastrowid` есть только в SQLite."""
        if self.is_postgres:
            text = sql.rstrip().rstrip(';')
            if 'RETURNING' not in text.upper():
                text += ' RETURNING id'
            return connection.execute(text, params).fetchone()[0]
        return connection.execute(sql, params).lastrowid


def table_columns(connection, table: str) -> set:
    """Имена колонок таблицы — там, где код решает, нужна ли миграция.

    В SQLite это `PRAGMA table_info`, которого в Postgres нет; там же сведения
    лежат в `information_schema`. Без этого миграции пытались бы добавить уже
    существующую колонку.
    """
    if isinstance(connection, PostgresConnection):
        # Только своя схема, как в table_exists: одноимённая таблица из другой
        # схемы подсунула бы чужие колонки, и нужный ALTER тихо пропустился бы.
        return {row[0] for row in connection.execute(
            'SELECT column_name FROM information_schema.columns '
            'WHERE table_schema = current_schema() AND table_name = ?',
            (table,))}
    return {row[1] for row in connection.execute(f'PRAGMA table_info("{table}")')}


def table_exists(connection, table: str) -> bool:
    """Есть ли таблица. В SQLite это `sqlite_master`, в Postgres — каталог."""
    if isinstance(connection, PostgresConnection):
        return connection.execute(
            'SELECT 1 FROM information_schema.tables '
            'WHERE table_schema = current_schema() AND table_name = ?', (table,)).fetchone() is not None
    return connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone() is not None


def as_database(target) -> Database:
    """Путь, строка подключения или уже готовая `Database`.

    Хранилища принимают любое из трёх, поэтому тесты и скрипты продолжают
    передавать путь к файлу, а продакшен — строку подключения Postgres.
    """
    if isinstance(target, Database):
        return target
    return Database(target)


def database_for(name: str, *, url: str = '', path=None) -> Database:
    """Одна база на сервис: в Postgres все таблицы живут в одной базе, в
    SQLite — каждая в своём файле, как было."""
    if url and is_postgres_url(url):
        return Database(url, name=name)
    return Database(path, name=name)
