"""Один слой доступа к базе: Postgres в продакшене, SQLite локально и в тестах.

Зачем так. На Railway у приложения нет диска, а SQLite — это файл, поэтому
рабочие данные живут в Postgres и переживают выкат. Но 538 тестов не должны
требовать поднятого сервера: для них остаётся файловый SQLite, и набор тестов
по-прежнему гоняется одной командой.

Расхождения диалектов узкие, потому что код изначально писался переносимо:
строк-фабрик нет (строки — кортежи), даты и деньги хранятся ISO-текстом и
сравниваются как текст, функций вида `strftime` в SQL нет. Остаётся механика:

* плейсхолдеры `?` → `%s`;
* `INTEGER PRIMARY KEY AUTOINCREMENT` → `GENERATED BY DEFAULT AS IDENTITY`;
* `BLOB` → `BYTEA`;
* `lastrowid` → `RETURNING id` (см. `insert_returning_id`);
* `BEGIN IMMEDIATE` → обычный `BEGIN`: в Postgres конфликт разрешает сама
  СУБД, а не блокировка файла;
* `INSERT OR IGNORE` → `INSERT ... ON CONFLICT DO NOTHING`;
* `PRAGMA` игнорируется.

Переписывание SQL выбрано осознанно вместо правки 242 запросов руками: две
механические замены проверяются тестом, а двести ручных правок в денежном коде
— нет.
"""
import re
import sqlite3
from contextlib import closing, contextmanager
from pathlib import Path
from urllib.parse import urlparse

from retro.runtime import secure_directory, secure_file

POSTGRES_SCHEMES = ('postgres', 'postgresql')


def is_postgres_url(value) -> bool:
    if not value:
        return False
    return urlparse(str(value)).scheme.split('+')[0] in POSTGRES_SCHEMES


# ── Перевод SQL ─────────────────────────────────────────────────────────────

_PLACEHOLDER = re.compile(r"""\?(?=(?:[^']*'[^']*')*[^']*$)""")


def to_postgres(sql: str) -> str:
    """SQLite-запрос → Postgres. Только механика, без разбора смысла."""
    sql = _PLACEHOLDER.sub('%s', sql)
    sql = re.sub(r'\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b',
                 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql, flags=re.I)
    sql = re.sub(r'\bINSERT\s+OR\s+IGNORE\s+INTO\b', 'INSERT INTO', sql, flags=re.I)
    sql = re.sub(r'\bINSERT\s+OR\s+REPLACE\s+INTO\b', 'INSERT INTO', sql, flags=re.I)
    sql = re.sub(r'\bBLOB\b', 'BYTEA', sql, flags=re.I)
    return sql


def needs_do_nothing(sql: str) -> bool:
    """`INSERT OR IGNORE` в Postgres требует явного `ON CONFLICT DO NOTHING`."""
    return bool(re.search(r'\bINSERT\s+OR\s+IGNORE\b', sql, flags=re.I)) \
        and 'ON CONFLICT' not in sql.upper()


def without_comments(sql: str) -> str:
    """SQL без ведущих строк-комментариев: по началу команды принимаются решения."""
    lines = [line for line in sql.strip().splitlines()
             if not line.strip().startswith('--')]
    return '\n'.join(lines).strip()


def statements(script: str):
    """`executescript` → отдельные команды. Точка с запятой внутри строк не
    встречается в нашем DDL, поэтому хватает простого разбиения."""
    return [part.strip() for part in script.split(';') if part.strip()]


# ── Соединения ──────────────────────────────────────────────────────────────

_DDL = re.compile(r'\s*(CREATE|ALTER|DROP)\s', re.I)
_INSERT_TABLE = re.compile(r'\bINSERT\s+(?:OR\s+\w+\s+)?INTO\s+([a-z_][a-z0-9_]*)', re.I)
_CREATE_TABLE = re.compile(
    r'CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-z_][a-z0-9_]*)\s*\((.*)', re.I | re.S)


def table_declares_id(statement: str) -> str | None:
    """Имя таблицы, если её DDL объявляет автономер `id`.

    Нужно, чтобы знать, где в Postgres дописывать `RETURNING id` вместо
    `lastrowid`. Список собирается из самого DDL, а не задаётся руками, — иначе
    новая таблица однажды тихо начнёт возвращать `None` вместо номера.
    """
    found = _CREATE_TABLE.search(statement)
    if not found:
        return None
    name, body = found.group(1), found.group(2)
    if re.search(r'\bid\s+(?:INTEGER|BIGINT)[^,]*\b(?:AUTOINCREMENT|IDENTITY)\b', body, re.I):
        return name
    return None


class PostgresConnection:
    """Обёртка, чтобы код хранилищ не различал диалекты.

    Нужна ровно для того, чтобы `connection.execute('... ?', params)` работал
    там же, где раньше работал sqlite3. Всё остальное отдаём psycopg как есть.
    """

    def __init__(self, raw, database=None):
        self._raw = raw
        self._database = database

    def execute(self, sql, params=()):
        if needs_do_nothing(sql):
            sql = sql.rstrip().rstrip(';') + ' ON CONFLICT DO NOTHING'
        text = to_postgres(sql)
        # Решения принимаем по самой команде, а не по комментарию перед ней.
        stripped = without_comments(text).upper()
        if stripped.startswith('CREATE TABLE'):
            self._remember_table(sql)
        if stripped.startswith('BEGIN IMMEDIATE'):
            text = 'BEGIN'
        if stripped.startswith('PRAGMA'):
            return _Empty()
        # Триггеры истории ставок существовали только в SQLite-базах, и их
        # сносит миграция. В Postgres сносить нечего, а синтаксис там иной
        # (нужен ON таблица), поэтому такие команды просто пропускаем.
        if stripped.startswith('DROP TRIGGER'):
            return _Empty()
        # `lastrowid` в psycopg не работает, поэтому у таблиц с автономером
        # добираем номер через RETURNING и отдаём его тем же полем.
        wants_id = False
        if self._database is not None and stripped.startswith('INSERT'):
            found = _INSERT_TABLE.search(text)
            if (found and found.group(1).lower() in self._database.tables_with_id
                    and 'RETURNING' not in stripped):
                text = text.rstrip().rstrip(';') + ' RETURNING id'
                wants_id = True
        cursor = self._raw.cursor()
        cursor.execute(text, tuple(params) if params else None)
        if wants_id:
            return _WithId(cursor)
        # SQLite фиксирует DDL сам, Postgres — нет, и схема откатывалась при
        # закрытии соединения. Схема у нас всегда идемпотентная (IF NOT EXISTS),
        # поэтому фиксируем её сразу, как это делает SQLite.
        if _DDL.match(stripped):
            self._raw.commit()
        return cursor

    def executemany(self, sql, rows):
        cursor = self._raw.cursor()
        cursor.executemany(to_postgres(sql), [tuple(row) for row in rows])
        return cursor

    def executescript(self, script):
        for statement in statements(script):
            self._remember_table(statement)
            self.execute(statement)
        return self

    def _remember_table(self, statement):
        name = table_declares_id(statement)
        if name and self._database is not None:
            self._database.tables_with_id.add(name)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()

    # `with closing(conn) as c, c:` — второй `with` открывает транзакцию.
    def __enter__(self):
        return self._raw.__enter__() and self

    def __exit__(self, *error):
        return self._raw.__exit__(*error)


class _WithId:
    """Курсор INSERT с уже прочитанным номером: код ждёт `lastrowid`."""

    def __init__(self, cursor):
        self._cursor = cursor
        row = cursor.fetchone()
        self.lastrowid = row[0] if row else None
        self.rowcount = cursor.rowcount

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


class _Empty:
    """Ответ на `PRAGMA`, которого в Postgres нет."""
    rowcount = 0
    lastrowid = None

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


class Database:
    """Откуда брать соединение. Хранилища получают её вместо пути к файлу."""

    def __init__(self, target, *, name=''):
        self.name = name
        self.url = str(target) if is_postgres_url(target) else ''
        self.path = None if self.url else Path(target)
        # Таблицы с автономером: заполняется при создании схемы, нужно для
        # RETURNING id вместо lastrowid.
        self.tables_with_id = set()
        if self.path is not None:
            secure_directory(self.path.parent)

    @property
    def is_postgres(self) -> bool:
        return bool(self.url)

    def connect(self):
        if not self.is_postgres:
            connection = sqlite3.connect(self.path, timeout=10)
            secure_file(self.path)
            connection.execute('PRAGMA foreign_keys = ON')
            return connection
        import psycopg
        return PostgresConnection(psycopg.connect(self.url, autocommit=False), self)

    @contextmanager
    def cursor(self):
        """Соединение на одну операцию, с закрытием."""
        with closing(self.connect()) as connection:
            yield connection

    def insert_returning_id(self, connection, sql, params=()):
        """Вставка с получением id: `lastrowid` есть только в SQLite."""
        if self.is_postgres:
            text = sql.rstrip().rstrip(';')
            if 'RETURNING' not in text.upper():
                text += ' RETURNING id'
            return connection.execute(text, params).fetchone()[0]
        return connection.execute(sql, params).lastrowid


def table_columns(connection, table: str) -> set:
    """Имена колонок таблицы — там, где код решает, нужна ли миграция.

    В SQLite это `PRAGMA table_info`, которого в Postgres нет; там же сведения
    лежат в `information_schema`. Без этого миграции пытались бы добавить уже
    существующую колонку.
    """
    if isinstance(connection, PostgresConnection):
        return {row[0] for row in connection.execute(
            'SELECT column_name FROM information_schema.columns WHERE table_name = ?',
            (table,))}
    return {row[1] for row in connection.execute(f'PRAGMA table_info("{table}")')}


def table_exists(connection, table: str) -> bool:
    """Есть ли таблица. В SQLite это `sqlite_master`, в Postgres — каталог."""
    if isinstance(connection, PostgresConnection):
        return connection.execute(
            'SELECT 1 FROM information_schema.tables '
            'WHERE table_schema = current_schema() AND table_name = ?', (table,)).fetchone() is not None
    return connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone() is not None


def as_database(target) -> Database:
    """Путь, строка подключения или уже готовая `Database`.

    Хранилища принимают любое из трёх, поэтому тесты и скрипты продолжают
    передавать путь к файлу, а продакшен — строку подключения Postgres.
    """
    if isinstance(target, Database):
        return target
    return Database(target)


def database_for(name: str, *, url: str = '', path=None) -> Database:
    """Одна база на сервис: в Postgres все таблицы живут в одной базе, в
    SQLite — каждая в своём файле, как было."""
    if url and is_postgres_url(url):
        return Database(url, name=name)
    return Database(path, name=name)
